"""add

Revision ID: 16f0af44dfbb
Revises: 584912d2a765
Create Date: 2019-03-20 23:46:24.371797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f0af44dfbb'
down_revision = '584912d2a765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('clicks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'clicks')
    # ### end Alembic commands ###
