"""add

Revision ID: 584912d2a765
Revises: 170b07a9cd5c
Create Date: 2019-03-19 19:06:48.996245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584912d2a765'
down_revision = '170b07a9cd5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'news', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_column('news', 'user_id')
    # ### end Alembic commands ###
