"""add

Revision ID: 5edcaaadde99
Revises: a1d970c1214f
Create Date: 2019-03-18 09:41:06.484761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5edcaaadde99'
down_revision = 'a1d970c1214f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('language', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('signature', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'signature')
    op.drop_column('user', 'language')
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
