"""add

Revision ID: f3733342f5a2
Revises: 5edcaaadde99
Create Date: 2019-03-18 15:32:51.206578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3733342f5a2'
down_revision = '5edcaaadde99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_url', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('joy', sa.String(length=100), nullable=True))
    op.drop_column('user', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_url', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('user', 'joy')
    op.drop_column('user', 'avatar_url')
    # ### end Alembic commands ###
